// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.31.1
// source: geo.proto

package geopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LookupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Addr  string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	// Дописать каждой системе её состав целиком: все анонсы. Второй ярус
	// бана -- «система целиком»; без просьбы ответ лёгкий, для корзин.
	ExpandAsn     bool `protobuf:"varint,2,opt,name=expand_asn,json=expandAsn,proto3" json:"expand_asn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_geo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_geo_proto_rawDescGZIP(), []int{0}
}

func (x *LookupRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *LookupRequest) GetExpandAsn() bool {
	if x != nil {
		return x.ExpandAsn
	}
	return false
}

type Country struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Country) Reset() {
	*x = Country{}
	mi := &file_geo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Country) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Country) ProtoMessage() {}

func (x *Country) ProtoReflect() protoreflect.Message {
	mi := &file_geo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Country.ProtoReflect.Descriptor instead.
func (*Country) Descriptor() ([]byte, []int) {
	return file_geo_proto_rawDescGZIP(), []int{1}
}

func (x *Country) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Country) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Эффективный кусок под адресом: анонс минус более узкие, включительно.
type Range struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         string                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Range) Reset() {
	*x = Range{}
	mi := &file_geo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_geo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_geo_proto_rawDescGZIP(), []int{2}
}

func (x *Range) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *Range) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

type ASN struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Asn   uint32                 `protobuf:"varint,1,opt,name=asn,proto3" json:"asn,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Анонс, накрывший адрес. Ответ на адрес несёт все накрывающие, от
	// самого узкого к самому широкому; эффективный -- первым.
	Prefix    string `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Effective bool   `protobuf:"varint,4,opt,name=effective,proto3" json:"effective,omitempty"`
	Range     *Range `protobuf:"bytes,5,opt,name=range,proto3" json:"range,omitempty"`
	// Состав системы; только при expand_asn.
	Prefixes      []string `protobuf:"bytes,6,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ASN) Reset() {
	*x = ASN{}
	mi := &file_geo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASN) ProtoMessage() {}

func (x *ASN) ProtoReflect() protoreflect.Message {
	mi := &file_geo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASN.ProtoReflect.Descriptor instead.
func (*ASN) Descriptor() ([]byte, []int) {
	return file_geo_proto_rawDescGZIP(), []int{3}
}

func (x *ASN) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *ASN) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ASN) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ASN) GetEffective() bool {
	if x != nil {
		return x.Effective
	}
	return false
}

func (x *ASN) GetRange() *Range {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *ASN) GetPrefixes() []string {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

type LookupResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Countries []*Country             `protobuf:"bytes,1,rep,name=countries,proto3" json:"countries,omitempty"`
	Asns      []*ASN                 `protobuf:"bytes,2,rep,name=asns,proto3" json:"asns,omitempty"`
	// Поколение снимка кодера: сменилось -- кэши клиентов устарели.
	Gen           uint64 `protobuf:"varint,3,opt,name=gen,proto3" json:"gen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_geo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_geo_proto_rawDescGZIP(), []int{4}
}

func (x *LookupResponse) GetCountries() []*Country {
	if x != nil {
		return x.Countries
	}
	return nil
}

func (x *LookupResponse) GetAsns() []*ASN {
	if x != nil {
		return x.Asns
	}
	return nil
}

func (x *LookupResponse) GetGen() uint64 {
	if x != nil {
		return x.Gen
	}
	return 0
}

var File_geo_proto protoreflect.FileDescriptor

const file_geo_proto_rawDesc = "" +
	"\n" +
	"\tgeo.proto\x12\x06geo.v1\"B\n" +
	"\rLookupRequest\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1d\n" +
	"\n" +
	"expand_asn\x18\x02 \x01(\bR\texpandAsn\"1\n" +
	"\aCountry\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"/\n" +
	"\x05Range\x12\x14\n" +
	"\x05start\x18\x01 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\tR\x03end\"\xa2\x01\n" +
	"\x03ASN\x12\x10\n" +
	"\x03asn\x18\x01 \x01(\rR\x03asn\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\x12\x1c\n" +
	"\teffective\x18\x04 \x01(\bR\teffective\x12#\n" +
	"\x05range\x18\x05 \x01(\v2\r.geo.v1.RangeR\x05range\x12\x1a\n" +
	"\bprefixes\x18\x06 \x03(\tR\bprefixes\"r\n" +
	"\x0eLookupResponse\x12-\n" +
	"\tcountries\x18\x01 \x03(\v2\x0f.geo.v1.CountryR\tcountries\x12\x1f\n" +
	"\x04asns\x18\x02 \x03(\v2\v.geo.v1.ASNR\x04asns\x12\x10\n" +
	"\x03gen\x18\x03 \x01(\x04R\x03gen2>\n" +
	"\x03Geo\x127\n" +
	"\x06Lookup\x12\x15.geo.v1.LookupRequest\x1a\x16.geo.v1.LookupResponseB.Z,github.com/exemt/placitum-shared/geopb;geopbb\x06proto3"

var (
	file_geo_proto_rawDescOnce sync.Once
	file_geo_proto_rawDescData []byte
)

func file_geo_proto_rawDescGZIP() []byte {
	file_geo_proto_rawDescOnce.Do(func() {
		file_geo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geo_proto_rawDesc), len(file_geo_proto_rawDesc)))
	})
	return file_geo_proto_rawDescData
}

var file_geo_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_geo_proto_goTypes = []any{
	(*LookupRequest)(nil),  // 0: geo.v1.LookupRequest
	(*Country)(nil),        // 1: geo.v1.Country
	(*Range)(nil),          // 2: geo.v1.Range
	(*ASN)(nil),            // 3: geo.v1.ASN
	(*LookupResponse)(nil), // 4: geo.v1.LookupResponse
}
var file_geo_proto_depIdxs = []int32{
	2, // 0: geo.v1.ASN.range:type_name -> geo.v1.Range
	1, // 1: geo.v1.LookupResponse.countries:type_name -> geo.v1.Country
	3, // 2: geo.v1.LookupResponse.asns:type_name -> geo.v1.ASN
	0, // 3: geo.v1.Geo.Lookup:input_type -> geo.v1.LookupRequest
	4, // 4: geo.v1.Geo.Lookup:output_type -> geo.v1.LookupResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_geo_proto_init() }
func file_geo_proto_init() {
	if File_geo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geo_proto_rawDesc), len(file_geo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geo_proto_goTypes,
		DependencyIndexes: file_geo_proto_depIdxs,
		MessageInfos:      file_geo_proto_msgTypes,
	}.Build()
	File_geo_proto = out.File
	file_geo_proto_goTypes = nil
	file_geo_proto_depIdxs = nil
}
